server:
  port: 8090
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt_fisunov_ver_2
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

#  sql:
#    init:
#      mode: embedded

