server:
  port: 8189
  servlet:
    context-path: /
jwt:
  secret: secret
  lifetime: 30m
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt_fisunov_ver_2
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#  sql:
#    init:
#      mode: embedded

